CREATE TABLE IF NOT EXISTS account ( id INT AUTO_INCREMENT, email VARCHAR(255), contentkey VARCHAR(1024), PRIMARY KEY (id) );
CREATE TABLE IF NOT EXISTS note ( id INT AUTO_INCREMENT, name VARCHAR(255), content TEXT, owner INT, revision INT NOT NULL DEFAULT 1, ctime INT, deleted INT(1) NOT NULL DEFAULT 0, PRIMARY KEY (id), FOREIGN KEY (owner) REFERENCES account(id) );
